### ISSUE TITLE
EFI CS2 Bluescreen

### ISSUE THREAD

**Issue by Klingy23** [ekknod/EC#123]
Hi, I have latest W11 23H2 (build 22631.3810), latest BIOS, MSI B450 Tomahawk MAX. about half a year ago, it worked but now it doesn't. Waiting for fix. Blue screen is either KMODE_EXCEPTION_NOT_HANDLED or SYSTEM_THREAD_EXCEPTION_NOT_HANDLED. Tried DISM repair and sfc /scannow. Have the same issue, nothing has worked yet.

**Comment by walterconticello** [comment]
I have the same problem!

**Comment by LifeGoal** [comment]
Seems to have been caused by the latest Windows Update. Try reverting it. Worked fine for me!

**Comment by khalilnajjar** [comment]
![image](https://github.com/user-attachments/assets/f689bfdc-0550-4702-9493-e928e8305adb)
This security update (KB5040442) is the culprit. 23H2 creates issues because this comes with it in addition to being a separate update to 22H2. If you have 23H2 you'll need to uninstall it then make sure to remove the KB5040442 if it re-installs itself under 22H2. I did exactly that and I'm back online. Careful though - this update keeps re-installing itself.

**Comment by AyzoxxRL** [comment]
helloo, i uninstall all this security update and i stop update of windows. But i have bluescreen after the game launch...
