### ISSUE TITLE
Aimbot doesnt work on linux

### ISSUE THREAD

**Issue by crabmiau** [ekknod/EC#52]
title

**Comment by ekknod** [comment]
I can't really check what is the problem, because network is not working with my Linux installation.

**Comment by krob64** [comment]
did some debugging a few weeks ago and iirc the issue is pops up here https://github.com/ekknod/EC/blob/main/cs2/shared/features.cpp#L670

math::get_fov() returns some garbage value, which i think will result in us never acquiring a target. didn't dig deeper than that as i am new to debugging on linux with gdb. might this be as simple as outdated offsets? esp also doesn't work, neither on kde nor on i3 (not surprising).

**Comment by ekknod** [comment]
Sounds like some address is indeed wrong.

**Comment by ekknod** [comment]
I might reinstall Linux some day so i can enable network again and test.
